### ISSUE TITLE
Read more link broken because it does not reference root namespace

### ISSUE THREAD

**Issue by zerodrama** [dokufreaks/plugin-folded#12]
If I have an article, "Cats", in the root namespace and an article, "Mice", in the namespace, "Prey" and I include a section from the "Cats" article in the "Mice" article, the Read more link will link to ":prey:cats", not ":cats".

If I include from an article in the namespace, "Food", it correctly links to ":food:title".

**Comment by LarsGit223** [comment]
Is this a use case of the include plugin alone or a combination of include and folder plugin?

I created the situation/pages described and I cannot see a problem. If I put a folded text or block in page "cats" and include the whole page or just the section with the folded block then everything seems to work properly.

Maybe this has been fixed in the meanwhile in the include plugin. Do you still encounter this problem if you update to the latest version of the include plugin?

Or did I understand something wrong?

**Comment by LarsGit223** [comment]
@zerodrama: I am closing this now as it seems to be outdated. If you still encounter this issue with the actual versions of the plugins folded and include then please re-open this issue.
